### ISSUE TITLE
:focus-visible global styling

### ISSUE THREAD

**Issue by Heydon** [bbc/gel#22]
The following lets us enhance to using `:focus-visible` where supported, and it should probably be used as a global style or adopted across all GelUI components. If focus styles do not show for mouse users, we can afford to make them much bolder and clearer :-)

```css
:focus-visible {
  outline: 2px solid; /* or whatever is applicable */
}

:focus:not(:focus-visible) {
  outline: none; /* ignored by UAs that don't support `:focus-visible`, meaning there is still default focus styling */
}
```

Currently, I use it in the tabs interface like

```css
  .gel-tabs [role="tab"]:focus-visible,
  .gel-tabs [role="tabpanel"]:focus-visible {
    outline: 2px solid;
    outline-offset: -2px;
  }

  .gel-tabs :focus:not(:focus-visible) {
    outline: none;
  }
```
